### ISSUE TITLE
I'm not so sure how to use this

### ISSUE THREAD

**Issue by Powtaitoe** [reed-jones/Neocities-php#1]
Title. I'm completely new to php and I'm not so sure how to run this or where to put my key, etc etc. I have composer and PHP installed already. But I don't know where to go from there

**Comment by reed-jones** [comment]
This library by itself is mostly just for uploading/modifying/deleting files you already have. I have mostly used it for writing CLI scripts, and for the jigsaw integration. 

Theres lots of ways to store your keys, but I personally would install [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) putting my keys in a `.env` file.

If your just starting to make your site I would suggest checking out [Jigsaw](https://jigsaw.tighten.co/docs/installation/) Its already got the `.env` stuff setup, and is pretty nice to use. Then you can install this, and set it up to deploy automatically whenever you run `./vendor/bin/jigsaw deploy production`

**Comment by Powtaitoe** [comment]
Right. Is it possible for neocities to support .PHP files?

**Comment by reed-jones** [comment]
not directly no, but that's how Jigsaw (or something else) can help. It compiles your .php files into static .html files that can get uploaded to neocities

**Comment by Powtaitoe** [comment]
Right. Thanks a lot. I just have to figure out on my own how to use Jigsaw with this. I have no clue what I'm doing xD

**Comment by reed-jones** [comment]
👍 Good luck, Hopefully their instructions help get you all set up

**Comment by Powtaitoe** [comment]
Do I install this into the jigsaw directory or my project's directory?

**Comment by reed-jones** [comment]
starting from scratch, I would make new project folder
```sh
mkdir myProject
```
install Jigsaw & Neocities-php
```sh
cd myProject
composer require tightenco/jigsaw
composer require reed-jones/neocities
```
'initialize' the Jigsaw stuff by running
```sh
./vendor/bin/jigsaw init
```
That will generate the project skeleton and add a bunch of files, one of them in the root of your project will be `bootstrap.php`

then 'install' the neocities integration by adding this to your bootstrap.php (It doesn't really matter where, but I would probably put it above that big comment block, so like line 7.
```php
Jigsaw::mixin(new \ReedJones\Neocities\NeocitiesDeployment($container));
```

Next is the keys, so create a file called `.env` (depending on your operating system & settings, this may be 'hidden' because it starts with a `'.'`)

now add your api key in there
```
NEO_CITIES_API_KEY="YOUR_API_KEY_HERE"
```

----

~... unfortunately, I just ran through these commands to double check it, and it seems theres a small bug with jigsaw which breaks this plugin. I opened a PR to fix it here: https://github.com/tightenco/jigsaw/pull/467 so hopefully it gets merged in soon 🤞  Until then you can still get started learning how to build a site with jigsaw, you just won't be able to use this library to automatically upload it to neocities. You can still build it with jigsaw using `./vendor/bin/jigsaw build production` , and then upload the contents of the `build_production` folder to neocities manually at https://neocities.org/dashboard~

**Comment by reed-jones** [comment]
Jigsaw has been updated & everything should be working properly again 👍 let me know if you run into troubles
